import NfValidate

/--
A valid sequence of edges from vertex `u` to vertex `v` where each edge exists in the `edges` list.
-/
inductive Path (edges : List Edge) : Var → Var → Type where
  | nil (u : Var) : Path edges u u
  | cons {w : Var} (e : Edge) (h_in : e ∈ edges) (p : Path edges e.dst w) : Path edges e.src w

/--
Calculates the sum of the weights of the edges in a given path.
-/
def pathWeight {edges : List Edge} {u v : Var} : Path edges u v → Int
  | Path.nil _ => 0
  | Path.cons e _ p => e.weight + pathWeight p

/--
A cycle is a path from a vertex to itself.
-/
abbrev Cycle (edges : List Edge) (u : Var) := Path edges u u

/--
A negative cycle is a cycle whose total weight is strictly less than 0.
-/
structure NegativeCycle (edges : List Edge) where
  u : Var
  cycle : Cycle edges u
  is_negative : pathWeight cycle < 0

/--
A context/distance map `d` satisfies an edge `e` if `d(e.dst) - d(e.src) ≤ e.weight`.
Equivalently: `d(e.dst) ≤ d(e.src) + e.weight`.
-/
def SatisfiesEdge (d : Var → Int) (e : Edge) : Prop :=
  d e.dst - d e.src ≤ e.weight

/--
A context `d` satisfies a whole graph (list of edges) if it satisfies every edge in the graph.
-/
def SatisfiesGraph (d : Var → Int) (edges : List Edge) : Prop :=
  ∀ e ∈ edges, SatisfiesEdge d e

/--
Path Inequality Lemma: If a context `d` satisfies a graph,
then for any `Path` from `u` to `v` with total weight `W`, `d(v) - d(u) ≤ W`.
-/
theorem path_inequality {edges : List Edge} {u v : Var} (d : Var → Int)
  (h_sat : SatisfiesGraph d edges) (p : Path edges u v) :
  d v - d u ≤ pathWeight p := by
  induction p with
  | nil _ =>
    simp [pathWeight]
  | cons e h_in p' ih =>
    simp [pathWeight]
    have h_e := h_sat e h_in
    unfold SatisfiesEdge at h_e
    omega

/--
Negative Cycle Contradiction Theorem: If a graph contains a `NegativeCycle`,
then no valid context `d` can exist that satisfies the graph.
-/
theorem no_valid_context_for_negative_cycle {edges : List Edge}
  (nc : NegativeCycle edges) (d : Var → Int) :
  ¬ SatisfiesGraph d edges := by
  intro h_sat
  have h_path := path_inequality d h_sat nc.cycle
  have h_neg := nc.is_negative
  omega

/--
Equality Semantics: If a graph contains both forward and backward edges with weight 0
between `x` and `y` (as generated by `Formula.eq`), then any satisfying context `d`
must assign `d(x) = d(y)`.
-/
theorem equality_semantics {edges : List Edge} {x y : Var} (d : Var → Int)
  (h_sat : SatisfiesGraph d edges)
  (h_fwd : { src := x, dst := y, weight := 0 } ∈ edges)
  (h_bwd : { src := y, dst := x, weight := 0 } ∈ edges) :
  d x = d y := by
  have h1 := h_sat _ h_fwd
  have h2 := h_sat _ h_bwd
  dsimp [SatisfiesEdge] at h1 h2
  omega
