project:
  type: book
  output-dir: .
execute:
  cache: true
  freeze: auto
format:
  html:
    theme: cosmo
    code-link: true
    toc: true
    toc-location: left
book:
  title: "NF Sketches: Documentation"
  repo-url: https://github.com/ryanncode/nf-sketches
  chapters:
    - index.qmd
    - 01-parse-strat.qmd
    - 02-comblib.qmd
    - 03-exprograms.qmd
    - 04-nf-validate.qmd
    - 05-seq-embed.qmd
    - 06-untyped-comb.qmd
    - 07-transfinite.qmd
    - 08-categorical.qmd
    - 09-monism.qmd
