project:
  type: book
  output-dir: _book
execute:
  cache: true
  freeze: auto
format:
  html:
    theme: cosmo
    code-link: true
book:
  title: "NF Sketches: Documentation"
  chapters:
    - 01-intro.qmd
    - 02-parse-strat.qmd
    - 03-comblib.qmd
    - 04-exprograms.qmd
    - 05-nf-validate.qmd
    - 06-seq-embed.qmd
    - 07-untyped-comb.qmd
    - 08-transfinite.qmd
    - 09-categorical.qmd
    - 10-monism.qmd
