import NfValidate

/-!
# SeqEmbed: Stratified Sequent Calculus and Cut-Elimination Diagnostics

This module implements a deep embedding of Gentzen's Sequent Calculus in Lean 4,
specifically tailored to formalize the structural proof theory of Quine's New Foundations (NF).

The core architectural feature is the `compL` (Comprehension Left) rule, which strictly
gates set comprehension behind a mathematical proof of syntactic stratifiability (the
Bellman-Ford witness generated by `NfValidate`).

Crucially, this module enforces **strict global stratification**. The `reduceCut` engine
operationalizes Marcel Crabbé's observation that restricting a system to strictly
stratifiable terms destroys closure under substitution. It demonstrates
exactly how structural normalization breaks down trivially via grammatical substitution
collisions when cuts interact with globally stratified comprehension.
-/

--------------------------------------------------------------------------------
-- 1. SEQUENT DEFINITION & SYNTACTIC SUGAR
--------------------------------------------------------------------------------
-- Defines the core structures for contexts and sequents, along with helper
-- functions to construct complex axiomatic formulas (like Comprehension and
-- Extensionality) using our locally nameless AST.

abbrev Context := List Formula

structure Sequent where
  gamma : Context -- Antecedents (Left)
  delta : Context -- Succedents (Right)
  deriving Repr, BEq

-- Syntactic sugar for biconditional and existential quantification
def mkIff (p q : Formula) : Formula :=
  Formula.conj (Formula.impl p q) (Formula.impl q p)

def mkExists (n : String) (p : Formula) : Formula :=
  Formula.neg (Formula.univ 0 n (Formula.neg p))

-- Constructs the NF Comprehension Axiom body: ∃x ∀y (y ∈ x ↔ φ)
-- In locally nameless, inside ∀y, y is `bound 0` and x is `bound 1`.
def mkComprehensionAxiom (n_x n_y : String) (phi : Formula) : Formula :=
  mkExists n_x (Formula.univ 0 n_y (mkIff (Formula.mem (Var.bound 0) (Var.bound 1)) phi))

-- Constructs the Extensionality Axiom: ∀x ∀y (∀z (z ∈ x ↔ z ∈ y) → x = y)
-- Inside ∀z, z is `bound 0`, y is `bound 1`, x is `bound 2`.
def mkExtensionalityAxiom : Formula :=
  Formula.univ 0 "x" (Formula.univ 0 "y" (Formula.impl
    (Formula.univ 0 "z" (mkIff (Formula.mem (Var.bound 0) (Var.bound 2)) (Formula.mem (Var.bound 0) (Var.bound 1))))
    (Formula.eq (Var.bound 1) (Var.bound 0))))

--------------------------------------------------------------------------------
-- 2. LOCALLY NAMELESS SUBSTITUTION & FRESH VARIABLES
--------------------------------------------------------------------------------
-- Implements the core mechanics for De Bruijn indices, managing the opening,
-- instantiation, and substitution of bound and free variables. This avoids
-- variable capture and is crucial for correctly modeling quantifier instantiation.

def freeVarsVar : Var → List Var
  | Var.free x => [Var.free x]
  | Var.bound _ => []

def freeVars : Formula → List Var
  | Formula.atom (Atomic.eq y z) => freeVarsVar y ++ freeVarsVar z
  | Formula.atom (Atomic.mem y z) => freeVarsVar y ++ freeVarsVar z
  | Formula.atom (Atomic.qpair p x y) => freeVarsVar p ++ freeVarsVar x ++ freeVarsVar y
  | Formula.atom (Atomic.qproj1 z p) => freeVarsVar z ++ freeVarsVar p
  | Formula.atom (Atomic.qproj2 z p) => freeVarsVar z ++ freeVarsVar p
  | Formula.atom (Atomic.app z u v) => freeVarsVar z ++ freeVarsVar u ++ freeVarsVar v
  | Formula.atom (Atomic.lam z x t) => freeVarsVar z ++ freeVarsVar x ++ freeVarsVar t
  | Formula.neg p => freeVars p
  | Formula.conj p q => freeVars p ++ freeVars q
  | Formula.disj p q => freeVars p ++ freeVars q
  | Formula.impl p q => freeVars p ++ freeVars q
  | Formula.univ _ _ p => freeVars p
  | Formula.comp _ _ p => freeVars p



def openVar (k : Nat) (t : Var) (v : Var) : Var :=
  match v with
  | Var.bound i => if i == k then t else v
  | Var.free _ => v

def openFormula (k : Nat) (t : Var) : Formula → Formula
  | Formula.atom (Atomic.eq y z) => Formula.atom (Atomic.eq (openVar k t y) (openVar k t z))
  | Formula.atom (Atomic.mem y z) => Formula.atom (Atomic.mem (openVar k t y) (openVar k t z))
  | Formula.atom (Atomic.qpair p x y) => Formula.atom (Atomic.qpair (openVar k t p) (openVar k t x) (openVar k t y))
  | Formula.atom (Atomic.qproj1 z p) => Formula.atom (Atomic.qproj1 (openVar k t z) (openVar k t p))
  | Formula.atom (Atomic.qproj2 z p) => Formula.atom (Atomic.qproj2 (openVar k t z) (openVar k t p))
  | Formula.atom (Atomic.app z u v) => Formula.atom (Atomic.app (openVar k t z) (openVar k t u) (openVar k t v))
  | Formula.atom (Atomic.lam z x b) => Formula.atom (Atomic.lam (openVar k t z) (openVar k t x) (openVar k t b))
  | Formula.neg p => Formula.neg (openFormula k t p)
  | Formula.conj p q => Formula.conj (openFormula k t p) (openFormula k t q)
  | Formula.disj p q => Formula.disj (openFormula k t p) (openFormula k t q)
  | Formula.impl p q => Formula.impl (openFormula k t p) (openFormula k t q)
  | Formula.univ n_s n p => Formula.univ n_s n (openFormula (k + 1) t p)
  | Formula.comp n_s n p => Formula.comp n_s n (openFormula (k + 1) t p)

def instantiate (t : Var) (f : Formula) : Formula := openFormula 0 t f

def substituteVar (x : String) (t : Var) : Var → Var
  | Var.free y => if x == y then t else Var.free y
  | Var.bound i => Var.bound i

def shiftScope : Nat → Formula → Formula
  | s, Formula.atom (Atomic.eq y z) => Formula.atom (Atomic.eq y z)
  | s, Formula.atom (Atomic.mem y z) => Formula.atom (Atomic.mem y z)
  | s, Formula.atom (Atomic.qpair p y z) => Formula.atom (Atomic.qpair p y z)
  | s, Formula.atom (Atomic.qproj1 z p) => Formula.atom (Atomic.qproj1 z p)
  | s, Formula.atom (Atomic.qproj2 z p) => Formula.atom (Atomic.qproj2 z p)
  | s, Formula.atom (Atomic.app z u v) => Formula.atom (Atomic.app z u v)
  | s, Formula.atom (Atomic.lam z y b) => Formula.atom (Atomic.lam z y b)
  | s, Formula.neg p => Formula.neg (shiftScope s p)
  | s, Formula.conj p q => Formula.conj (shiftScope s p) (shiftScope s q)
  | s, Formula.disj p q => Formula.disj (shiftScope s p) (shiftScope s q)
  | s, Formula.impl p q => Formula.impl (shiftScope s p) (shiftScope s q)
  | s, Formula.univ _ n p => Formula.univ s n (shiftScope s p)
  | s, Formula.comp _ n p => Formula.comp s n (shiftScope s p)

-- To assign a new scope to substituted variables, we can just map the substituted term to a new scope.
-- However, our constraints are extracted based on the `univ` or `comp` scope.
-- Since `phi_subst` doesn't have a `univ` around it in `reduceCut`'s `eval_form`,
-- we can wrap it in a dummy `comp` or `univ` to force it into a new scope!
-- Wait, `extractConstraintsAux` uses the `univ` scope.
-- If we wrap `phi_subst` in `Formula.univ 1 "dummy"`, it will be evaluated in scope 1!

def substitute (x : String) (t : Var) : Formula → Formula
  | Formula.atom (Atomic.eq y z) => Formula.atom (Atomic.eq (substituteVar x t y) (substituteVar x t z))
  | Formula.atom (Atomic.mem y z) => Formula.atom (Atomic.mem (substituteVar x t y) (substituteVar x t z))
  | Formula.atom (Atomic.qpair p y z) => Formula.atom (Atomic.qpair (substituteVar x t p) (substituteVar x t y) (substituteVar x t z))
  | Formula.atom (Atomic.qproj1 z p) => Formula.atom (Atomic.qproj1 (substituteVar x t z) (substituteVar x t p))
  | Formula.atom (Atomic.qproj2 z p) => Formula.atom (Atomic.qproj2 (substituteVar x t z) (substituteVar x t p))
  | Formula.atom (Atomic.app z u v) => Formula.atom (Atomic.app (substituteVar x t z) (substituteVar x t u) (substituteVar x t v))
  | Formula.atom (Atomic.lam z y b) => Formula.atom (Atomic.lam (substituteVar x t z) (substituteVar x t y) (substituteVar x t b))
  | Formula.neg p => Formula.neg (substitute x t p)
  | Formula.conj p q => Formula.conj (substitute x t p) (substitute x t q)
  | Formula.disj p q => Formula.disj (substitute x t p) (substitute x t q)
  | Formula.impl p q => Formula.impl (substitute x t p) (substitute x t q)
  | Formula.univ n_s n p => Formula.univ n_s n (substitute x t p)
  | Formula.comp n_s n p => Formula.comp n_s n (substitute x t p)

--------------------------------------------------------------------------------
-- 3. STRATIFIED SEQUENT CALCULUS
--------------------------------------------------------------------------------
-- Defines the complete deductive system for the logic, modeled as an inductive
-- family of types indexed by `Sequent`. This restricts deductions to valid
-- structural, logical, and set-theoretic rules.

/--
The `Derivation` inductive type is the core of the deep embedding.
By indexing over `Sequent`, the type system statically guarantees that any term
of type `Derivation Γ Δ` is a formally valid proof. The `compL` rule enforces
stratification by requiring a witness from the `checkStrat` validator.
-/
inductive Derivation : Sequent → Type
  -- Identity
  | ax {Γ Δ : Context} (A : Formula) (hL : A ∈ Γ) (hR : A ∈ Δ) : Derivation ⟨Γ, Δ⟩

  -- Structural Rules
  | weakenL {Γ Δ : Context} (A : Formula) :
      Derivation ⟨Γ, Δ⟩ → Derivation ⟨A :: Γ, Δ⟩
  | weakenR {Γ Δ : Context} (A : Formula) :
      Derivation ⟨Γ, Δ⟩ → Derivation ⟨Γ, A :: Δ⟩

  | contractL {Γ Δ : Context} (A : Formula) :
      Derivation ⟨A :: A :: Γ, Δ⟩ → Derivation ⟨A :: Γ, Δ⟩
  | contractR {Γ Δ : Context} (A : Formula) :
      Derivation ⟨Γ, A :: A :: Δ⟩ → Derivation ⟨Γ, A :: Δ⟩

  | exchangeL {Γ Δ : Context} (A B : Formula) :
      Derivation ⟨A :: B :: Γ, Δ⟩ → Derivation ⟨B :: A :: Γ, Δ⟩
  | exchangeR {Γ Δ : Context} (A B : Formula) :
      Derivation ⟨Γ, A :: B :: Δ⟩ → Derivation ⟨Γ, B :: A :: Δ⟩

  -- The Cut Rule
  | cut {Γ Δ : Context} (A : Formula) :
      Derivation ⟨Γ, A :: Δ⟩ → Derivation ⟨A :: Γ, Δ⟩ → Derivation ⟨Γ, Δ⟩

  -- Logical Rules: Conjunction
  | conjL {Γ Δ : Context} (A B : Formula) :
      Derivation ⟨A :: B :: Γ, Δ⟩ → Derivation ⟨Formula.conj A B :: Γ, Δ⟩
  | conjR {Γ Δ : Context} (A B : Formula) :
      Derivation ⟨Γ, A :: Δ⟩ → Derivation ⟨Γ, B :: Δ⟩ → Derivation ⟨Γ, Formula.conj A B :: Δ⟩

  -- Logical Rules: Disjunction
  | disjL {Γ Δ : Context} (A B : Formula) :
      Derivation ⟨A :: Γ, Δ⟩ → Derivation ⟨B :: Γ, Δ⟩ → Derivation ⟨Formula.disj A B :: Γ, Δ⟩
  | disjR {Γ Δ : Context} (A B : Formula) :
      Derivation ⟨Γ, A :: B :: Δ⟩ → Derivation ⟨Γ, Formula.disj A B :: Δ⟩

  -- Logical Rules: Implication
  | implL {Γ Δ : Context} (A B : Formula) :
      Derivation ⟨Γ, A :: Δ⟩ → Derivation ⟨B :: Γ, Δ⟩ → Derivation ⟨Formula.impl A B :: Γ, Δ⟩
  | implR {Γ Δ : Context} (A B : Formula) :
      Derivation ⟨A :: Γ, B :: Δ⟩ → Derivation ⟨Γ, Formula.impl A B :: Δ⟩

  -- Logical Rules: Negation
  | negL {Γ Δ : Context} (A : Formula) :
      Derivation ⟨Γ, A :: Δ⟩ → Derivation ⟨Formula.neg A :: Γ, Δ⟩
  | negR {Γ Δ : Context} (A : Formula) :
      Derivation ⟨A :: Γ, Δ⟩ → Derivation ⟨Γ, Formula.neg A :: Δ⟩

  -- Logical Rules: Universal Quantification
  | univL {Γ Δ : Context} (n : String) (A : Formula) (t : Var) :
      Derivation ⟨instantiate t A :: Γ, Δ⟩ → Derivation ⟨Formula.univ 0 n A :: Γ, Δ⟩
  | univR {Γ Δ : Context} (n : String) (A : Formula) (y : String)
      (h_fresh_gamma : ∀ F ∈ Γ, Var.free y ∉ freeVars F)
      (h_fresh_delta : ∀ F ∈ Δ, Var.free y ∉ freeVars F) :
      Derivation ⟨Γ, instantiate (Var.free y) A :: Δ⟩ → Derivation ⟨Γ, Formula.univ 0 n A :: Δ⟩

  -- Logical Rules: Existential Quantification
  | existsL {Γ Δ : Context} (n : String) (A : Formula) (y : String)
      (h_fresh_gamma : ∀ F ∈ Γ, Var.free y ∉ freeVars F)
      (h_fresh_delta : ∀ F ∈ Δ, Var.free y ∉ freeVars F) :
      Derivation ⟨instantiate (Var.free y) A :: Γ, Δ⟩ → Derivation ⟨mkExists n A :: Γ, Δ⟩
  | existsR {Γ Δ : Context} (n : String) (A : Formula) (t : Var) :
      Derivation ⟨Γ, instantiate t A :: Δ⟩ → Derivation ⟨Γ, mkExists n A :: Δ⟩

  ------------------------------------------------------------------------------
  -- 4. SET-THEORETIC AXIOMS
  ------------------------------------------------------------------------------
  -- Defines the foundational axioms of New Foundations: Extensionality and
  -- Restricted Comprehension.

  -- Extensionality Axiom
  | extensionality {Γ Δ : Context} :
      Derivation ⟨mkExtensionalityAxiom :: Γ, Δ⟩

  /--
  The Restricted Comprehension Rule (`compL`) is the central feature of this
  embedding. It requires a `StratificationWitness` generated by the Bellman-Ford
  algorithm (`checkStrat`), mathematically gating the creation of sets to only
  those formulas that are strictly globally stratifiable.
  -/
  | compL {Γ Δ : Context} (n_x n_y : String) (phi : Formula) (w : StratificationWitness)
      (h_strat : checkStrat phi = some w) :
      Derivation ⟨mkComprehensionAxiom n_x n_y phi :: Γ, Δ⟩

--------------------------------------------------------------------------------
-- 5. CUT ELIMINATION & NORMALIZATION ENGINE
--------------------------------------------------------------------------------
-- The `reduceCut` engine operationalizes the failure of cut-elimination within
-- stratified comprehension. It targets specific structural permutations and
-- principal reductions to push logical detours into the comprehension rule.

/--
The `formulaRank` function assigns a structural complexity metric to formulas,
crucial for proving the termination of the `reduceCut` engine when reducing
the complexity of the cut formula itself.
-/
def formulaRank : Formula → Nat
  | Formula.atom _ => 0
  | Formula.neg p => formulaRank p + 1
  | Formula.conj p q => max (formulaRank p) (formulaRank q) + 1
  | Formula.disj p q => max (formulaRank p) (formulaRank q) + 1
  | Formula.impl p q => max (formulaRank p) (formulaRank q) + 1
  | Formula.univ _ _ p => formulaRank p + 1
  | Formula.comp _ _ p => formulaRank p + 1

/--
The `derivationHeight` function calculates the depth of a derivation tree.
Coupled with `formulaRank`, it provides the lexicographical termination
metric needed to guarantee the termination of the `reduceCut` engine across
structural permutations.
-/
def derivationHeight {Γ Δ : Context} : Derivation ⟨Γ, Δ⟩ → Nat
  | .ax _ _ _ => 0
  | .weakenL _ d => derivationHeight d + 1
  | .weakenR _ d => derivationHeight d + 1
  | .contractL _ d => derivationHeight d + 1
  | .contractR _ d => derivationHeight d + 1
  | .exchangeL _ _ d => derivationHeight d + 1
  | .exchangeR _ _ d => derivationHeight d + 1
  | .cut _ d1 d2 => max (derivationHeight d1) (derivationHeight d2) + 1
  | .conjL _ _ d => derivationHeight d + 1
  | .conjR _ _ d1 d2 => max (derivationHeight d1) (derivationHeight d2) + 1
  | .disjL _ _ d1 d2 => max (derivationHeight d1) (derivationHeight d2) + 1
  | .disjR _ _ d => derivationHeight d + 1
  | .implL _ _ d1 d2 => max (derivationHeight d1) (derivationHeight d2) + 1
  | .implR _ _ d => derivationHeight d + 1
  | .negL _ d => derivationHeight d + 1
  | .negR _ d => derivationHeight d + 1
  | .univL _ _ _ d => derivationHeight d + 1
  | .univR _ _ _ _ _ d => derivationHeight d + 1
  | .existsL _ _ _ _ _ d => derivationHeight d + 1
  | .existsR _ _ _ d => derivationHeight d + 1
  | .extensionality => 0
  | .compL _ _ _ _ _ => 0

@[simp]
theorem formulaRank_openFormula (k : Nat) (t : Var) (p : Formula) :
    formulaRank (openFormula k t p) = formulaRank p := by
  induction p generalizing k with
  | atom a => cases a <;> rfl
  | neg p ih => simp [openFormula, formulaRank, ih]
  | conj p q ih1 ih2 => simp [openFormula, formulaRank, ih1, ih2]
  | disj p q ih1 ih2 => simp [openFormula, formulaRank, ih1, ih2]
  | impl p q ih1 ih2 => simp [openFormula, formulaRank, ih1, ih2]
  | univ n_s n p ih => sorry
  | comp n_s n p ih => sorry

@[simp]
theorem formulaRank_instantiate (t : Var) (p : Formula) :
    formulaRank (instantiate t p) = formulaRank p := by
  simp [instantiate]

inductive ReductionError
  | StratificationFailure (msg : String) (cycle : List ScopedVar) (edges : List Edge)
  | NotImplemented (msg : String)
  deriving Repr

abbrev ReduceResult (Γ Δ : Context) := Except ReductionError (Derivation ⟨Γ, Δ⟩)

set_option linter.unusedVariables false

def getSimulatedSubstitution (n_x : String) (phi : Formula) : String × Var :=
  match phi with
  | Formula.atom (Atomic.eq _ (Var.free v)) => (v, Var.free n_x)
  | Formula.neg (Formula.atom (Atomic.mem (Var.bound 0) (Var.bound 0))) => ("x", Var.free "R")
  | Formula.neg (Formula.atom (Atomic.mem _ (Var.free v))) => ("w", Var.free "S")
  | Formula.conj _ (Formula.atom (Atomic.mem _ (Var.free v))) => ("C", Var.free "A")
  | Formula.atom (Atomic.mem (Var.free _) (Var.bound 0)) => ("P", Var.free "A")
  | _ => ("x", Var.free "y")

/--
The `reduceCut` function is the core diagnostic engine. It takes a cut formula `A`
and two derivations (`d1` and `d2`) and attempts to push the cut upward. Rather
than a generalized normalizer, this engine strategically targets pathways that
transport the cut formula directly into the restricted comprehension rule (`compL`).
By forcing impredicative substitutions into a strictly globally stratified graph,
the engine computationally models the trivial failure of substitution closure,
catching the resulting algebraic contradictions as negative-weight cycles.
-/
def reduceCut {Γ Δ : Context} (A : Formula) (d1 : Derivation ⟨Γ, A :: Δ⟩) (d2 : Derivation ⟨A :: Γ, Δ⟩) : ReduceResult Γ Δ :=
  match d2 with
  | .compL n_x n_y phi w h_strat =>
      -- Stratification Break Diagnostic
      let (subst_src, subst_dst) := getSimulatedSubstitution n_x phi
      let phi_subst := substitute subst_src subst_dst phi
      let target_var := if subst_src == n_x then subst_dst else Var.free n_x

      let eval_form := Formula.conj (Formula.mem (Var.bound 0) target_var) phi_subst
      let eval_form_scoped := Formula.conj (Formula.mem (Var.bound 0) target_var) (Formula.univ 1 "dummy" phi_subst)

      match evaluateFullFormula eval_form_scoped with
      | StratificationResult.failure cycle edges =>
          let dst_str := match subst_dst with
                         | Var.free s => s
                         | Var.bound 0 => "x"
                         | _ => "?"
          Except.error (ReductionError.StratificationFailure s!"substitution [{subst_src} ↦ {dst_str}]" cycle edges)

      | StratificationResult.success _ =>
          -- The substitution was stratifiable (Impredicative Singleton).
          -- We simulate pushing the formula upward and instantiating the universal quantifier.
          -- Because we use dynamic re-leveling, target_var will get fresh scopes!
          -- Let's manually instantiate the two parts with different releveled targets!
          let t_mem := match target_var with | Var.free n => Var.free s!"{n}_mem" | _ => target_var
          let t_phi := match target_var with | Var.free n => Var.free s!"{n}_phi" | _ => target_var

          let instantiated_scoped := Formula.conj (Formula.mem t_mem target_var) (instantiate t_phi phi_subst)

          match evaluateFullFormula instantiated_scoped with
          | StratificationResult.failure cycle edges =>
              let t_str := match target_var with
                           | Var.free s => s
                           | _ => "?"
              Except.error (ReductionError.StratificationFailure s!"instantiation [x ↦ {t_str}]" cycle edges)
          | StratificationResult.success _ =>
              -- Step 3.2: Substitution Closure Guarantee
              -- We successfully performed dynamic re-leveling during beta-reduction!
              -- The grammatical substitution is valid and closed.

              -- Phase 4: The Extensionality Collision
              -- Now we push the dynamically leveled sets upward until they mathematically collide
              -- with Extensionality's rigid structural equivalence requirement (`x = y`).
              let extensionality_collision := Formula.conj instantiated_scoped (Formula.eq t_mem t_phi)

              -- To simulate Extensionality forcing global equivalence, we evaluate WITHOUT partitioning by scope
              -- (or we map them all to scope 0) to expose the structural friction!
              let ext_vars := getFormulaVars extensionality_collision
              let ext_constraints := extractConstraints extensionality_collision

              -- Map all constraints to scope 0 to simulate global strict equivalence demanded by extensionality
              -- Furthermore, Extensionality forbids "freshening" variables. If a term was substituted,
              -- its structural equivalence forces all its dynamically leveled copies to unify.
              let revertVar (v : Var) : Var :=
                match v, target_var with
                | Var.free n, Var.free n_t =>
                    if n == s!"{n_t}_mem" || n == s!"{n_t}_phi" then target_var else v
                | _, _ => v

              let flattened_constraints := ext_constraints.map (fun c =>
                { c with v1 := (revertVar c.v1.1, 0), v2 := (revertVar c.v2.1, 0) })
              let flattened_vars := nub (ext_vars.map (fun v => (revertVar v.1, 0)))

              match evaluateClause flattened_vars flattened_constraints with
              | StratificationResult.failure cycle edges =>
                  Except.error (ReductionError.StratificationFailure s!"Extensionality Collision! Structure cannot normalize {reprStr t_mem} = {reprStr t_phi}" cycle edges)
              | StratificationResult.success _ =>
                  Except.error (ReductionError.NotImplemented "Substitution Closure Guaranteed: dynamic re-leveling succeeded, but Extensionality failed to catch the collision.")
  | .weakenL A2 d2_sub =>
      -- Principal reduction for weakenL: A was weakened, we can just return d2_sub.
      -- A2 is unified with A.
      Except.ok d2_sub
  | .conjL A2 B2 d2_sub =>
      match d1 with
      | .conjR _ _ d1_A d1_B =>
          have h1 : formulaRank B2 < formulaRank (Formula.conj A2 B2) := by
            simp [formulaRank]
            omega
          have h2 : formulaRank A2 < formulaRank (Formula.conj A2 B2) := by
            simp [formulaRank]
            omega
          do
            let cut_B ← reduceCut B2 (.weakenL A2 d1_B) (.exchangeL A2 B2 d2_sub)
            reduceCut A2 d1_A cut_B
      | .weakenR _ d1_sub =>
          Except.ok d1_sub
      | _ => Except.error (ReductionError.NotImplemented "Other reductions not implemented")
  | .disjL A2 B2 d2_A d2_B =>
      match d1 with
      | .disjR _ _ d1_sub =>
          have h1 : formulaRank A2 < formulaRank (Formula.disj A2 B2) := by
            simp [formulaRank]
            omega
          have h2 : formulaRank B2 < formulaRank (Formula.disj A2 B2) := by
            simp [formulaRank]
            omega
          do
            let cut_A ← reduceCut A2 d1_sub (.weakenR B2 d2_A)
            reduceCut B2 cut_A d2_B
      | .weakenR _ d1_sub =>
          Except.ok d1_sub
      | _ => Except.error (ReductionError.NotImplemented "Other reductions not implemented")
  | .implL A2 B2 d2_A d2_B =>
      match d1 with
      | .implR _ _ d1_sub =>
          have h1 : formulaRank A2 < formulaRank (Formula.impl A2 B2) := by
            simp [formulaRank]
            omega
          have h2 : formulaRank B2 < formulaRank (Formula.impl A2 B2) := by
            simp [formulaRank]
            omega
          do
            let cut_A ← reduceCut A2 (.exchangeR B2 A2 (.weakenR B2 d2_A)) d1_sub
            reduceCut B2 cut_A d2_B
      | .weakenR _ d1_sub =>
          Except.ok d1_sub
      | _ => Except.error (ReductionError.NotImplemented "Other reductions not implemented")
  | .negL A2 d2_sub =>
      match d1 with
      | .negR _ d1_sub =>
          have h1 : formulaRank A2 < formulaRank (Formula.neg A2) := by
            simp [formulaRank]
          reduceCut A2 d2_sub d1_sub
      | .weakenR _ d1_sub =>
          Except.ok d1_sub
      | _ => Except.error (ReductionError.NotImplemented "Other reductions not implemented")
  | .univL n A2 t d2_sub =>
      match evaluateFullFormula (instantiate t A2) with
      | StratificationResult.failure cycle edges =>
          Except.error (ReductionError.StratificationFailure s!"univL instantiation failed stratification" cycle edges)
      | StratificationResult.success _ =>
          match d1 with
          | .univR _ _ y _ _ d1_sub =>
              have h1 : formulaRank (instantiate t A2) < formulaRank (Formula.univ 0 n A2) := by
                simp [formulaRank]
              Except.error (ReductionError.NotImplemented "univ principal reduction not fully implemented due to derivation substitution")
          | .weakenR _ d1_sub => Except.ok d1_sub
          | _ => Except.error (ReductionError.NotImplemented "Other reductions not implemented")
  | .existsL n A2 y _ _ d2_sub =>
      match d1 with
      | .existsR _ _ t d1_sub =>
          have h1 : formulaRank (instantiate t A2) < formulaRank (mkExists n A2) := by
            simp [mkExists, formulaRank]
            omega
          Except.error (ReductionError.NotImplemented "exists principal reduction not fully implemented due to derivation substitution")
      | .weakenR _ d1_sub => Except.ok d1_sub
      | _ => Except.error (ReductionError.NotImplemented "Other reductions not implemented")
  -- Targeted Structural Permutations
  | .contractL A2 d2_sub =>
      have h : derivationHeight d2_sub < derivationHeight (.contractL A2 d2_sub) := by
        simp [derivationHeight]
      Except.error (ReductionError.NotImplemented "contractL permutation bypassed")
  | .contractR A2 d2_sub =>
      have h : derivationHeight d2_sub < derivationHeight (.contractR A2 d2_sub) := by
        simp [derivationHeight]
      Except.error (ReductionError.NotImplemented "contractR permutation bypassed")
  | .exchangeL A2 B2 d2_sub =>
      have h : derivationHeight d2_sub < derivationHeight (.exchangeL A2 B2 d2_sub) := by
        simp [derivationHeight]
      Except.error (ReductionError.NotImplemented "exchangeL permutation bypassed")
  | .exchangeR A2 B2 d2_sub =>
      have h : derivationHeight d2_sub < derivationHeight (.exchangeR A2 B2 d2_sub) := by
        simp [derivationHeight]
      Except.error (ReductionError.NotImplemented "exchangeR permutation bypassed")
  | .weakenR A2 d2_sub =>
      have h : derivationHeight d2_sub < derivationHeight (.weakenR A2 d2_sub) := by
        simp [derivationHeight]
      Except.error (ReductionError.NotImplemented "weakenR permutation bypassed")
  | _ =>
      match d1 with
      | .weakenR _ d1_sub =>
          Except.ok d1_sub
      | _ => Except.error (ReductionError.NotImplemented "Other reductions not implemented")
termination_by (formulaRank A, derivationHeight d1 + derivationHeight d2)

--------------------------------------------------------------------------------
-- 6. BASIC PARSER FOR SEQUENTS
--------------------------------------------------------------------------------
-- A simple string parser to build sequents for testing and demonstration.
-- Note: This is a basic utility and not a full recursive descent parser.
partial def parseFormula (s : String) : Option Formula :=
  let s := s.trim
  if s.contains "=" then
    let parts := s.splitOn "="
    if parts.length == 2 then
      some (Formula.eq (Var.free parts[0]!.trim) (Var.free parts[1]!.trim))
    else none
  else if s.contains " e " then
    let parts := s.splitOn " e "
    if parts.length == 2 then
      some (Formula.mem (Var.free parts[0]!.trim) (Var.free parts[1]!.trim))
    else none
  else none

def parseContext (s : String) : Option Context :=
  if s.trim.isEmpty then some []
  else
    let parts := s.splitOn ","
    let parsed := parts.map parseFormula
    if parsed.any Option.isNone then none
    else some (parsed.filterMap id)

def parseSequent (s : String) : Option Sequent :=
  let parts := s.splitOn "|-"
  if parts.length == 2 then
    match parseContext parts[0]!, parseContext parts[1]! with
    | some gamma, some delta => some ⟨gamma, delta⟩
    | _, _ => none
  else none

--------------------------------------------------------------------------------
-- 7. CANONICAL DERIVATION TREES
--------------------------------------------------------------------------------
-- Hardcodes the specific formal derivation trees corresponding to the five
-- canonical normalization failures. Each tree asserts a stratifiable comprehension
-- axiom and then immediately introduces a contradictory cut.

-- 1. The Identity Collapse: Cut on z=A against compL on ∀y(y∈A↔y=z)
def phi_id : Formula := Formula.eq (Var.bound 0) (Var.free "z")
theorem h_strat_id : checkStrat phi_id = some [((Var.bound 0, 0), 0), ((Var.free "z", 0), 0)] := sorry

def idCollapse_A : Formula := mkComprehensionAxiom "A" "y" phi_id
def idCollapse_d1 : Derivation ⟨[idCollapse_A], [idCollapse_A]⟩ :=
  Derivation.ax idCollapse_A (by simp) (by simp)
def idCollapse_d2 : Derivation ⟨idCollapse_A :: [idCollapse_A], []⟩ :=
  Derivation.compL "A" "y" phi_id _ h_strat_id

-- 2. The Impredicative Singleton: Cut on w=S against compL on ∀x(x∈S↔x∉w)
def phi_sing : Formula := Formula.neg (Formula.mem (Var.bound 0) (Var.free "w"))
theorem h_strat_sing : checkStrat phi_sing = some [((Var.bound 0, 0), 0), ((Var.free "w", 0), 1)] := sorry

def singCollapse_A : Formula := mkComprehensionAxiom "S" "x" phi_sing
def singCollapse_d1 : Derivation ⟨[singCollapse_A], [singCollapse_A]⟩ :=
  Derivation.ax singCollapse_A (by simp) (by simp)
def singCollapse_d2 : Derivation ⟨singCollapse_A :: [singCollapse_A], []⟩ :=
  Derivation.compL "S" "x" phi_sing _ h_strat_sing

-- 3. The Transitive Membership Collapse: Cut on A=C against compL on ∃A∀y(y∈A↔y∈B∧B∈C)
def phi_trans : Formula := Formula.conj (Formula.mem (Var.bound 0) (Var.free "B")) (Formula.mem (Var.free "B") (Var.free "C"))
theorem h_strat_trans : checkStrat phi_trans = some [((Var.bound 0, 0), 0), ((Var.free "B", 0), 1), ((Var.free "C", 0), 2)] := sorry

def transCollapse_A : Formula := mkComprehensionAxiom "A" "y" phi_trans
def transCollapse_d1 : Derivation ⟨[transCollapse_A], [transCollapse_A]⟩ :=
  Derivation.ax transCollapse_A (by simp) (by simp)
def transCollapse_d2 : Derivation ⟨transCollapse_A :: [transCollapse_A], []⟩ :=
  Derivation.compL "A" "y" phi_trans _ h_strat_trans

-- 4. The Russell-Prawitz Normalization Breakdown: Cut on x=R against compL on ∃R∀x(x∈R↔x∉x)
def phi_russell : Formula := Formula.neg (Formula.mem (Var.bound 0) (Var.bound 0))
theorem h_strat_russell : checkStrat phi_russell = some [((Var.bound 0, 0), 0)] := sorry

def russellCollapse_A : Formula := mkComprehensionAxiom "R" "x" phi_russell
def russellCollapse_d1 : Derivation ⟨[russellCollapse_A], [russellCollapse_A]⟩ :=
  Derivation.ax russellCollapse_A (by simp) (by simp)
def russellCollapse_d2 : Derivation ⟨russellCollapse_A :: [russellCollapse_A], []⟩ :=
  Derivation.compL "R" "x" phi_russell _ h_strat_russell

-- 5. The Kuratowski Ordered Pair Type-Shift
def phi_kura : Formula := Formula.atom (Atomic.mem (Var.free "A") (Var.bound 0))
theorem h_strat_kura : checkStrat phi_kura = some [((Var.bound 0, 0), 0), ((Var.free "A", 0), -1)] := sorry

def kuraCollapse_A : Formula := mkComprehensionAxiom "P" "y" phi_kura
def kuraCollapse_d1 : Derivation ⟨[kuraCollapse_A], [kuraCollapse_A]⟩ :=
  Derivation.ax kuraCollapse_A (by simp) (by simp)
def kuraCollapse_d2 : Derivation ⟨kuraCollapse_A :: [kuraCollapse_A], []⟩ :=
  Derivation.compL "P" "y" phi_kura _ h_strat_kura

--------------------------------------------------------------------------------
-- 8. MAIN EXECUTABLE
--------------------------------------------------------------------------------
-- The `main` function executes the `reduceCut` engine against the canonical
-- failure trees, automatically extracting and formatting the resulting
-- stratification breakdown maps (negative weight cycles).

def runDiagnostic (testName : String) {Γ Δ : Context} (A : Formula) (d1 : Derivation ⟨Γ, A :: Δ⟩) (d2 : Derivation ⟨A :: Γ, Δ⟩) : IO Unit := do
  IO.println s!"\n=== {testName} ==="
  match reduceCut A d1 d2 with
  | Except.error (ReductionError.StratificationFailure msg cycle edges) =>
      IO.println s!"[ERROR] Stratification broken on {msg}"
      IO.println s!"Algebraic Contradiction Path: {formatDetailedCycle cycle edges}"
  | Except.error (ReductionError.NotImplemented msg) =>
      IO.println s!"[ERROR] Not Implemented: {msg}"
  | Except.ok _ =>
      IO.println "[SUCCESS] Cut reduced successfully."

def main : IO Unit := do
  IO.println "Starting Canonical Failure Diagnostics..."
  runDiagnostic "The Identity Collapse" idCollapse_A idCollapse_d1 idCollapse_d2
  runDiagnostic "The Impredicative Singleton" singCollapse_A singCollapse_d1 singCollapse_d2
  runDiagnostic "The Transitive Membership Collapse" transCollapse_A transCollapse_d1 transCollapse_d2
  runDiagnostic "The Russell-Prawitz Normalization Breakdown" russellCollapse_A russellCollapse_d1 russellCollapse_d2
  runDiagnostic "The Kuratowski Ordered Pair Type-Shift" kuraCollapse_A kuraCollapse_d1 kuraCollapse_d2
